-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 17:03:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pruebalaptop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pruebalaptop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruebalaptop` DEFAULT CHARACTER SET utf8mb4 ;
USE `pruebalaptop` ;

-- -----------------------------------------------------
-- Table `pruebalaptop`.`pc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebalaptop`.`pc` ;

CREATE TABLE IF NOT EXISTS `pruebalaptop`.`pc` (
  `ID` INT(10) NOT NULL,
  `Company` VARCHAR(20) NOT NULL,
  `TypeName` VARCHAR(90) NOT NULL,
  `Inches` FLOAT NOT NULL,
  `ScreenResolution` VARCHAR(90) NOT NULL,
  `Cpu` VARCHAR(90) NOT NULL,
  `Ram` VARCHAR(10) NOT NULL,
  `Memory` VARCHAR(90) NOT NULL,
  `Gpu` VARCHAR(90) NOT NULL,
  `OpSys` VARCHAR(90) NOT NULL,
  `Weight` FLOAT NOT NULL,
  `Price` FLOAT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
